config/routes.rb
Rails.application.routes.draw do

  get '/autocomplete_address' => "orders#autocomplete_address"
  get 'dashboard' => "orders#dashboard"
  devise_for :users
  root to: "home#index"
  resources :orders
  get 'login' => "sessions#new"
  post'login'   => 'sessions#create'
  get '/logout.id' => 'sessions#destroy', as: "destroy"
  delete "/logout.id" => "admins#destroy"

  get "/searches" => "search#index"

  patch "order_modify" => 'orders#update' , as: "order_modify"
  get "dashboard" => "admins#show"

  post "search_number" => 'search#search_number'

  post "tracker" => 'search#tracker'

  post "transporter" => 'search#transporter'

  post "pick_up_date" => 'search#pick_up_date'

  get "export" => 'orders#export'

  get '/statistic/:id' => 'orders#statistic'

  get "/show_details" => 'orders#show_details'

  get "calendar" => "orders#calendar"

  get "payment_overdue" => "orders#payment_overdue"

end

app/models/order.rb
class Order < ActiveRecord::Base
	include ActiveModel::Dirty

	# attribute_will_change!

	# :tel_no, :account_no, :payment_rate, :payment_with_gst, :payment_advance ,:payment_paid, :payment_commision, :payment_balance, :rate, :billing_name, :billing_rate, :billing_amount, :billing_received, :billing_balance, :invoice_date, :invoice, :payment_calculate_gst, :payment_reverse_calculate_gst, :billing_calculate_gst, :billing_reverse_calculate_gst, :gst_total_value, :gst_billing_total_value, :billing_with_gst


# def name
#     @name
#   end

#   def name=(val)
#     name_will_change! unless val == @name
#     @name = val
#   end

#   def save
#     # do persistence work

#     changes_applied
#   end

#   def reload!
#     # get the values from the persistence layer

#     clear_changes_information
#   end

#   def rollback!
#     restore_attributes
#   end



	include PgSearch
	pg_search_scope :search_by_name, ( lambda do |name_part, query|
		raise ArgumentError unless [:shipper, :transporter, :datetime, :no, :pick_up_pic_no, :phone_no, :tel_no ].include?(name_part)
		{:against => name_part,
			:query => query
		}
	end)


	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end
	belongs_to :user
	has_many :records
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		@order = Order.new
	end

  def autocomplete_address
@target = []
order = Order.all
order.each do |x|
  @target << x.pick_up_address_1 
  @target << x.pick_up_address_2 
  @target << x.pick_up_address_3  
  @target << x.pick_up_address_4  
  @target << x.drop_point_address_1  
  @target <<  x.drop_point_address_2 
  @target << x.drop_point_address_3 
  @target << x.drop_point_address_4 
  @target <<  x.shipper_address   
  @target.flatten.reject{|x| x == ""}.uniq!
  #reject any duplicates
  @target & @target
end

#
number = params[:address].length - 1
@back = []
@target.each do |x|
  if x[0..(number)].downcase == params[:address].downcase
    @back << x
  end
end
    render json: @back
  end

	def dashboard
		@order = Order.paginate(:page => params[:page], :per_page => 20).order('no ASC')
		respond_to do |format|
			format.html
			format.csv { send_data @order.to_csv }
    format.xls # { send_data @products.to_csv(col_sep: "\t") }
  end
end

def create
	# a = current_user.email
	@order = Order.create(order_params)
  # UserMailer.create_edit_order(@order, a).deliver
	redirect_to root_path(@order)
end

def edit
  @order = Order.find(params[:id])
end

def show
	@order = Order.find(params[:id])
end

def update
	@order = Order.find(params[:id])
	a = current_user.email
	@order.update(order_params)
  UserMailer.edit_order(@order, a).deliver
  redirect_to root_path(@order)
      # Handle a successful update.
    end


    def destroy
    	@order = Order.find(params[:id])

    	@order.destroy
    # flash[:success] = "User deleted"
    redirect_to root_path
  end


  def export
  	@order = Order.order(:name)
  	respond_to do |format|
  		format.html
  		format.csv { send_data @order.to_csv }
    format.xls # { send_data @products.to_csv(col_sep: "\t") }
  end
end


def statistic
  @order = []
  a = params[:id]
  @today = params[:id]
  
  time = Time.parse(a)
  compare = time.strftime("%Y-%m-%d")
  Order.all.each do |x|
    if !x.datetime.nil? && (x.datetime.strftime("%Y-%m-%d") == compare)
      @order << x
    end
  end
   @order 
end


def show_details
  @callback = []
  response = Order.find_by(id: params[:response])
  @callback << response.inquiry_date
  @callback << response.no
  @callback << response.shipper
  @callback << response.shipper_address
  @callback << response.transporter
  @callback << response.truck_size
  @callback << response.details
  @callback << response.remarks
  @callback << response.notes
  @callback << response.datetime
  @callback << response.goods_description
  @callback << response.pick_up_address_1
  @callback << response.pick_up_pic_no_1
  @callback << response.pick_up_address_2
  @callback << response.pick_up_pic_no_2
  @callback << response.pick_up_address_3
  @callback << response.pick_up_pic_no_3
  @callback << response.pick_up_address_4
  @callback << response.pick_up_pic_no_4
  @callback << response.special_request
  @callback << response.drop_point_address_1
  @callback << response.drop_point_pic_no_1
  @callback << response.drop_point_address_2
  @callback << response.drop_point_pic_no_2
  @callback << response.drop_point_address_3
  @callback << response.drop_point_pic_no_3
  @callback << response.drop_point_address_4
  @callback << response.drop_point_pic_no_4
  @callback << response.trucks_capacity 
  @callback << response.truck_reg_no 
  @callback << response.name
  @callback << response.ic 
  @callback << response.phone_no
  @callback << response.delivery_date
  @callback << response.do_request_date
  @callback << response.do_collection_date
  @callback << response.do_number
  @callback << response.total_tonne
  @callback << response.payment_name
  @callback << response.tel_no
  @callback << response.account_no
  @callback << response.rate
  @callback << response.payment_rate
  @callback << response.gst_total_value
  @callback << response.payment_with_gst
  @callback << response.payment_advance
  @callback << response.payment_paid
  @callback << response.payment_commision
  @callback << response.payment_balance
  @callback << response.billing_name
  @callback << response.billing_rate
  @callback << response.billing_amount
  @callback << response.gst_billing_total_value
  @callback << response.billing_with_gst
  @callback << response.billing_received
  @callback << response.billing_balance
  @callback << response.invoice_date
  @callback << response.invoice
  render json: @callback
end

def calendar
  order = Order.all
  @orders_by_date = order.group_by(&:datetime)
  @date = params[:date] ? Date.parse(params[:date]) : Date.today
  
end

def payment_overdue
  @payment_overdue = []
  Order.all.each do |x|
    if !(x.created_at..x.created_at+604800).cover?(Time.now) && !(x.payment_balance == 0)
      @payment_overdue << x
    end
  end
end


private


def order_params
	params.require(:order).permit(:no, :pod, :loading_status, :pick_up, :drop, :closing_date, :remarks)
end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <div class="col-md-6">
    <%= form_for @order  do |f| %>
    <h3> BASIC INFO</h3>

    <dt><%= f.label :no %></dt>
    <dd><%= f.text_field :no, class: 'form-control' %></dd>

    <dt><%= f.label :pod %></dt>
    <dd><%= f.text_field :pod, class: 'form-control' %></dd>

    <dt><%= f.label :loading_status %></dt>
    <dd><%= f.text_field :loading_status, class: 'form-control' %></dd>

    <dt><%= f.label :container_required %></dt>
    <dd><%= f.text_field :pick_up, class: "date_of_birth"  %></dd>

    <dt><%= f.label :container_received %></dt>
    <dd><%= f.text_field :drop, class: "date_of_birth"  %></dd>

    <dt><%= f.label :closing_date %></dt>
    <dd><%= f.text_field :closing_date, class: "date_of_birth"  %></dd>
    <br>

    <dt><%= f.label :remarks %></dt>
    <dd><%= f.text_field :remarks, class: 'form-control' %></dd>
    <br><br>
    <dd><%= f.submit "Save", class: "btn btn-primary" %>   <%= link_to "Back" , dashboard_path, class: "btn btn-primary", :"data-no-turbolink" => true  %></dd>


  </div>
</div>
<%end%>

app/views/orders/calendar.html.erb
 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

<h1>Calendar</h1>
<h2 id="month"><%= link_to "<", date: @date.prev_month %>
<%= @date.strftime("%B %Y")%>
<%= link_to ">", date: @date.next_month %></h2>
<div id="articles">
<%= calendar @date do |date|%>
<%= date.day %>

<%if @orders_by_date[date] %>

<ul>
  <% @orders_by_date[date].first(4).each do |order|%>

  <li><%= order.transporter%>(<%= link_to order.remarks, order %>)</li><%end%>

  <% if @orders_by_date[date].count > 4 %>
    <li><a href="statistic/<%= date %>">See More</a></li>
    <%end%>

</ul>

<%end%>

<%end%>
</div>
 </div>

app/views/orders/dashboard.html.erb
<!DOCTYPE html>


<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="http://getbootstrap.com/favicon.ico">

  <title>Dashboard Template for Bootstrap</title>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>
      <div class="container">
        <h1 class="page-header">Order Tracker</h1>
        <h2 class="sub-header">Recent Order that had been made</h2>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>No</th>
                <th>Pod</th>
                <th>Loading Status</th>
                <th>Container Required</th>
                <th>Container Received</th>
                <th>Closing date</th>
                <th>Remarks</th>
                <th>Edit</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% @order.each do |x| %>
                <td><%= x.no %></td>
                <td><%= x.pod %></td>
                <td><%= x.loading_status %></td>
                <td><%= x.pick_up %></td>
                <td><%= x.drop %></td>
                <td><%= x.closing_date %></td>
                <td><%= x.remarks %></td>
                <td><a href="/orders/<%= x.id%>/edit" data-no-turbolink = true>+</a></td>
              </tr>
              <%end%>
              <br>
               <%= will_paginate @order %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <style>
  .divOutside {
    border-bottom:2px blue solid;
    width:200px;
    padding-bottom:5px;
    padding-top:5px;
  }
  </style>
  <!-- Modal -->
  <!-- Button trigger modal -->

  

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
  </html>

app/views/orders/edit.html.erb
   

   <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
  $(function() {
  $( ".date_of_birth" ).datepicker({
    changeMonth: true,
    changeYear: true,
          dateFormat: 'dd-mm-yy'
  });

  });
  </script>

 <%= render 'form' %>

 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
     <%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' } %>
   </div>

app/views/orders/show.html.erb
 <!-- source for changing color at menu  -->
<link rel='stylesheet' href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<style>
ul {
  list-style-type: none;
}
ul li {
  margin-bottom: 10px;
}
.btn-custom {
  background-color: transparent;
  box-shadow: 3px 3px 3px 3px #888888;
}
.action-button li button.active {
  background-color: grey; color:white;
}
</style>

<script>
$(document).on('ready page:load', function(){
  $('.action-button button').click(function() {
    $('.action-button button.active').removeClass('active');
    $(this).addClass('active');
  })
});
</script>

<div class="row">
  <div class="col-md-2 col-md-offset-2">
    <br><br><br><br>
    <br>
    <br><br>
    <ul class="action-button">

    <li><a href="#order" aria-controls="order" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Order</button></a></li>
    <br>
    <li><a href="#personal_info" aria-controls="personal_info" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Pick Up info</button></a></li>
    <br>
    <li><a href="#employment_info" aria-controls="employment_info"role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Drop Point</button></a></li>
    <br>
    <li><a href="#others_info" aria-controls="others_info" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Driver</button></a></li>
    <br>
    <li><a href="#system_info" aria-controls="system_info" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Delivery Flow</button></a></li>
    <br>
  
    <li><a href="#payment_info" aria-controls="system_info" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Payment info</button></a></li>
    <br>
    <li><a href="#billing_info" aria-controls="system_info" role="tab" data-toggle="tab"><button type="button" class="btn btn-custom btn-block">Billing info</button></a></li>
    </ul>

  </div>
<%= form_for :order, url: order_path  do |f| %>
  <div class="col-md-4 col-md-offset-1">
    <div>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="order">
          <br><br>
          <dl class="dl-horizontal">
            <dt><%= f.label :inquiry_date %></dt>
            <dd><%= @order.datetime %></dd>
            <br>
            <dt><%= f.label :no %></dt>
            <dd><%= @order.no %></dd>
            <br>
            <dt><%= f.label :shipper  %></dt>
            <dd><%= @order.shipper %></dd>
            <br>
            <dt><%= f.label :shipper_address  %></dt>
            <dd><%= @order.shipper_address %></dd>
            <br>
            <dt><%= f.label :transporter %></dt>
            <dd><%= @order.transporter %></dd>
            <br>
            <dt><%= f.label :truck_size %></dt>
            <dd><%= @order.truck_size %></dd>
            <br>
            <dt><%= f.label :route %></dt>
            <dd><%= @order.remarks %></dd>
            <br>
            <%if current_user.email != "mu@ikargo.com" %>
            <dt><%= f.label(:payment, "Rate") %></dt>
            <dd><%= @order.payment_with_gst %></dd>
            <%end%>
            <br>
            <dt><%= f.label :notes%></dt>
            <dd><%= @order.notes %></dd>
            <br>
          </dl>
        </ul>
      </div>

      <div role="tabpanel" class="tab-pane" id="personal_info">
        <br><br>
        <dl class="dl-horizontal">
          <dt><%= f.label :pick_up_address_1 %></dt>
          <dd><%= @order.pick_up_address_1 %></dd>
          <br>
          <dt><%= f.label :pick_up_pic_no_1 %></dt>
          <dd><%= @order.pick_up_pic_no_1 %></dd>
          <br>
          <dt><%= f.label :pick_up_address_2 %></dt>
          <dd><%= @order.pick_up_address_2 %></dd>
          <br>
          <dt><%= f.label :pick_up_pic_no_2 %></dt>
          <dd><%= @order.pick_up_pic_no_2 %></dd>
          <br>
          <dt><%= f.label :pick_up_address_3 %></dt>
          <dd><%= @order.pick_up_address_3 %></dd>
          <br>
          <dt><%= f.label :pick_up_pic_no_3 %></dt>
          <dd><%= @order.pick_up_pic_no_3 %></dd>
          <br>
          <dt><%= f.label :pick_up_address_4 %></dt>
          <dd><%= @order.pick_up_address_4 %></dd>
          <br>
          <dt><%= f.label :pick_up_pic_no_4 %></dt>
          <dd><%= @order.pick_up_pic_no_4 %></dd>
          <br>
          <dt><%= f.label :goods_description %></dt>
          <dd><%= @order.goods_description %></dd>
          <br>
          <dt><%= f.label :datetime  %></dt>
          <dd><%= @order.datetime %></dd>
          <br>
          <dt><%= f.label :special_request %></dt>
          <dd><%= @order.special_request %></dd>
        </dl>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="employment_info">
      <dl class="dl-horizontal">
        <br><br>
        <dt><%= f.label :drop_point_date %></dt>
        <dd><%= @order.drop_point_date %></dd>
        <br>
        <dt><%= f.label :drop_point_address_1 %></dt>
        <dd><%= @order.drop_point_address_1 %></dd>
        <br>
        <dt><%= f.label :drop_point_pic_no_1 %></dt>
        <dd><%= @order.drop_point_pic_no_1 %></dd>
        <br>
        <dt><%= f.label :drop_point_address_2 %></dt>
        <dd><%= @order.drop_point_address_2 %></dd>
        <br>
        <dt><%= f.label :drop_point_pic_no_2 %></dt>
        <dd><%= @order.drop_point_pic_no_2 %></dd>
        <br>
        <dt><%= f.label :drop_point_address_3 %></dt>
        <dd><%= @order.drop_point_address_3 %></dd>
        <br>
        <dt><%= f.label :drop_point_pic_no_3 %></dt>
        <dd><%= @order.drop_point_pic_no_3 %></dd>
        <br>
        <dt><%= f.label :drop_point_address_4 %></dt>
        <dd><%= @order.drop_point_address_4 %></dd>
        <br>
        <dt><%= f.label :drop_point_pic_no_4 %></dt>
        <dd><%= @order.drop_point_pic_no_4 %></dd>
        <br>
        <dt><%= f.label :special_request %></dt>
        <dd><%= @order.special_request %></dd>
        <br>
      </dl>
    </div>

    <div role="tabpanel" class="tab-pane" id="others_info">
      <dl class="dl-horizontal">
        <br><br>
        <dt><%= f.label :trucks_capacity %></dt>
        <dd><%= @order.trucks_capacity %></dd>
        <br>
        <dt><%= f.label :truck_reg_no %></dt>
        <dd><%= @order.truck_reg_no %></dd>
        <br>
        <dt><%= f.label :name %></dt>
        <dd><%= @order.name %></dd>
        <br>
        <dt><%= f.label :ic %></dt>
        <dd><%= @order.ic %></dd>
        <br>
        <dt><%= f.label :phone_no %></dt>
        <dd><%= @order.phone_no %></dd>
        <br>
        <dt><%= f.label :driver_remarks %></dt>
        <dd><%= @order.driver_remarks %></dd>
      </dl>
    </div>

    <div role="tabpanel" class="tab-pane" id="system_info">
      <dl class="dl-horizontal">
        <br><br>
        <dt><%= f.label :delivery_date %></dt>
        <dd><%= @order.delivery_date %></dd>
        <br>

        <dt><%= f.label :do_request_date %></dt>
        <dd><%= @order.do_request_date %></dd>
        <br>

        <dt><%= f.label :do_collection_date %></dt>
        <dd><%= @order.do_collection_date %></dd>
        <br>

        <dt><%= f.label :do_number %></dt>
        <dd><%= @order.do_number %></dd>
        <br>

        <dt><%= f.label :total_tonne %></dt>
        <dd><%= @order.total_tonne %></dd>
         <br>

        <dt><%= f.label :deliveredy_status %></dt>
        <dd><%= @order.delivered %></dd>
        <br>
      </dl>
    </div>

    <div role="tabpanel" class="tab-pane" id="payment_info">
      <dl class="dl-horizontal">
        <br><br>
        <dt><%= f.label :payment_name %></dt>
        <dd><%= @order.payment_name %></dd>
        <br>
        <dt><%= f.label :tel_no %></dt>
        <dd><%= @order.tel_no %></dd>
        <br>
        <dt><%= f.label :account_no %></dt>
        <dd><%= @order.account_no %></dd>
        <br>
        <dt><%= f.label :rate %></dt>
        <dd><%= @order.rate %></dd>
        <br>
        <dt><%= f.label :payment_rate %></dt>
        <dd><%= @order.payment_rate %></dd>
        <br>
        <dt><%= f.label(:gst_total_value, "6% GST")%></dt>
        <dd>  <%= @order.gst_total_value %>
        </dd>
        <br>
        <dt><%= f.label(:gst_total_value, "Total After GST") %></dt>
        <dd><%= @order.payment_with_gst %></dd>
        <br>
        <dt><%= f.label :advance %></dt>
        <dd><%= @order.payment_advance %></dd>
        <br>
        <dt><%= f.label :commision %></dt>
        <dd><%= @order.payment_commision %></dd>
        <br>
        <dt><%= f.label :paid %></dt>
        <dd><%= @order.payment_paid %></dd>
        <br>
        <dt><%= f.label :balance %></dt>
        <dd><%= @order.payment_balance %></dd>

      </dl>
    </div>
    <div role="tabpanel" class="tab-pane" id="billing_info">
      <dl class="dl-horizontal">
        <br><br>
        <dt><%= f.label :name %></dt>
        <dd><%= @order.billing_name %></dd>
        <br>
<dt><%= f.label(:billing_rate, "rate") %></dt>
        <dd><%= @order.billing_rate%></dd>
        <br>
        <dt><%= f.label :amount %></dt>
        <dd><%= @order.billing_amount%></dd>
        <br>
        <dt><%= f.label(:gst_billing_total_value, "6% GST" )%></dt>
        <dd id="billing_gst"><%= @order.gst_billing_total_value%></dd>
        <br>

<dt><%= f.label(:billing_with_gst, "MASTER TOTAL") %></dt>
        <dd><%= @order.billing_with_gst%></dd>
        <br>


        <dt><%= f.label :billing_received %></dt>
        <dd><%= @order.billing_received%></dd>
        <br>

        <dt><%= f.label :billing_balance %></dt>
        <dd><%= @order.billing_balance%></dd>
        <br>

        <dt><%= f.label :invoice_date %></dt>
        <dd><%= @order.invoice_date  %></dd>
        <br>
        <dt><%= f.label :invoice %></dt>
        <dd><%= @order.invoice %></dd>
        <br>

      </dl>
    </div>
    <dd><%= link_to "Edit", edit_order_path, class: "btn btn-primary", style: "margin-right:10px;", :"data-no-turbolink" => true %>
      
      <%= link_to "Back" , dashboard_path, class: "btn btn-primary", :"data-no-turbolink" => true %>

      <%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' }, style: "margin-right:10px;", style: "margin-right:10px;margin-left: 500px;" %>
    </dd>
  </dl>
</div>
</div>
</div>
</div>
<%end%>
</div>

app/views/orders/statistic.html.erb
 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
<h1> Shipment on <%= @today %></h1>

<table class= "table table-bordered" style="width:100%;">
  <tr>
<td>No</td>
    <td>Transporter</td>
    <td>Routes</td>
  </tr>
  <tr>
    <% @order.each_with_index do |x, y| %>
  <td><%= y+1%></td>
    <td><%= x.transporter%> </td>
    <td><%= x.remarks%></td>
  </tr>
  <%end%>

</table>
</div>