config/routes.rb
Rails.application.routes.draw do

  get '/autocomplete_address' => "orders#autocomplete_address"
  get 'dashboard' => "orders#dashboard"
  devise_for :users
  root to: "home#index"
  resources :orders
  get 'login' => "sessions#new"
  post'login'   => 'sessions#create'
  get '/logout.id' => 'sessions#destroy', as: "destroy"
  delete "/logout.id" => "admins#destroy"

  get "/searches" => "search#index"

  patch "order_modify" => 'orders#update' , as: "order_modify"
  get "dashboard" => "admins#show"

  post "search_number" => 'search#search_number'

  post "tracker" => 'search#tracker'

  post "transporter" => 'search#transporter'

  post "pick_up_date" => 'search#pick_up_date'

  get "export" => 'orders#export'

  get '/statistic/:id' => 'orders#statistic'

  get "/show_details" => 'orders#show_details'

  get "calendar" => "orders#calendar"

  get "payment_overdue" => "orders#payment_overdue"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>DeliveryOrder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
  <link href="https://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/1.10.7/integration/jqueryui/dataTables.jqueryui.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/plug-ins/1.10.7/integration/jqueryui/dataTables.jqueryui.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">iKargo</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
          <li style="color:white; padding-top:15px;color:#9d9d9d;" class= "icon-bar">Signed in as <%= current_user.email %> as <%= current_user.party%></li>
          <li>      <%= link_to 'Create new order', orders_path, data:  { no_turbolink: true }%></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <%end%>
          
          
        </ul>
        
      </div>
    </div>
  </nav>
</div>


    <% flash.each do |name, msg|%>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <%end%>
    <%= yield %>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= debug(params) if Rails.env.development? %></p>
    </div>
  </body>
  </html>